#pragma once
#include "Wall.hpp"
#include "FlatMirror.hpp"
#include "FlatLens.hpp"
#include "CircularLens.hpp"
#include "CircularMirror.hpp"
#include "ArcMirror.hpp"
#include "ArcLens.hpp"
#include "Splitter.hpp"